revoke execute on function public.rls_auto_enable() from public;
revoke execute on function public.rls_auto_enable() from anon;
revoke execute on function public.rls_auto_enable() from authenticated;

create index if not exists audit_logs_actor_id_idx on public.audit_logs (actor_id);
create index if not exists cash_register_sessions_opened_by_idx on public.cash_register_sessions (opened_by);
create index if not exists cash_register_sessions_closed_by_idx on public.cash_register_sessions (closed_by);
create index if not exists combo_items_combo_id_idx on public.combo_items (combo_id);
create index if not exists expenses_paid_by_idx on public.expenses (paid_by);
create index if not exists inventory_movements_created_by_idx on public.inventory_movements (created_by);
create index if not exists inventory_movements_inventory_item_id_idx on public.inventory_movements (inventory_item_id);
create index if not exists order_item_extras_extra_id_idx on public.order_item_extras (extra_id);
create index if not exists order_items_combo_id_idx on public.order_items (combo_id);
create index if not exists order_items_crust_extra_id_idx on public.order_items (crust_extra_id);
create index if not exists order_items_flavor_a_id_idx on public.order_items (flavor_a_id);
create index if not exists order_items_flavor_b_id_idx on public.order_items (flavor_b_id);
create index if not exists order_items_order_id_idx on public.order_items (order_id);
create index if not exists order_items_product_id_idx on public.order_items (product_id);
create index if not exists order_items_size_id_idx on public.order_items (size_id);
create index if not exists order_status_events_actor_id_idx on public.order_status_events (actor_id);
create index if not exists order_status_events_order_id_idx on public.order_status_events (order_id);
create index if not exists orders_assigned_courier_id_idx on public.orders (assigned_courier_id);
create index if not exists orders_auth_user_id_idx on public.orders (auth_user_id);
create index if not exists orders_created_by_idx on public.orders (created_by);
create index if not exists payments_cash_session_id_idx on public.payments (cash_session_id);
create index if not exists payments_order_id_idx on public.payments (order_id);
create index if not exists payments_received_by_idx on public.payments (received_by);
create index if not exists pizza_flavor_prices_size_id_idx on public.pizza_flavor_prices (size_id);
create index if not exists print_jobs_order_id_idx on public.print_jobs (order_id);
create index if not exists print_jobs_requested_by_idx on public.print_jobs (requested_by);
create index if not exists products_inventory_item_id_idx on public.products (inventory_item_id);
create index if not exists purchase_items_inventory_item_id_idx on public.purchase_items (inventory_item_id);
create index if not exists purchase_items_purchase_id_idx on public.purchase_items (purchase_id);
create index if not exists purchases_purchased_by_idx on public.purchases (purchased_by);
create index if not exists purchases_supplier_id_idx on public.purchases (supplier_id);
create index if not exists recipes_extra_id_idx on public.recipes (extra_id);
create index if not exists recipes_flavor_id_idx on public.recipes (flavor_id);
create index if not exists recipes_inventory_item_id_idx on public.recipes (inventory_item_id);
create index if not exists recipes_size_id_idx on public.recipes (size_id);

create index if not exists orders_status_created_at_idx on public.orders (status, created_at desc);
create index if not exists orders_kind_status_idx on public.orders (kind, status);
create index if not exists order_status_events_created_at_idx on public.order_status_events (created_at desc);
create index if not exists inventory_movements_created_at_idx on public.inventory_movements (created_at desc);
create index if not exists purchases_purchased_at_idx on public.purchases (purchased_at desc);
create index if not exists expenses_paid_at_idx on public.expenses (paid_at desc);
create index if not exists print_jobs_created_at_idx on public.print_jobs (created_at desc);
